package com.honhai.foxconn.tankcrash;

public enum MapData {

        TEST_ROAD,
        TEST_PILLAR,

        ROAD_END_TOP,
        ROAD_END_RIGHT,
        ROAD_END_DOWN,
        ROAD_END_LEFT,
        ROAD_LINE_V,
        ROAD_LINE_H,
        ROAD_BEND_TR,
        ROAD_BEND_DR,
        ROAD_BEND_TL,
        ROAD_BEND_DL,
        ROAD_TRI_NT,
        ROAD_TRI_NR,
        ROAD_TRI_ND,
        ROAD_TRI_NL,
        ROAD_CROSS,

        RIVER_END_ALL,
        RIVER_END_TOP,
        RIVER_END_RIGHT,
        RIVER_END_DOWN ,
        RIVER_END_LEFT ,
        RIVER_LINE_V,
        RIVER_LINE_H ,
        RIVER_BEND_TR ,
        RIVER_BEND_DR ,
        RIVER_BEND_TL ,
        RIVER_BEND_DL ,
        RIVER_TRI_NT ,
        RIVER_TRI_NR ,
        RIVER_TRI_ND ,
        RIVER_TRI_NL ,
        RIVER_CROSS ,
        RIVER_SEA_CENTER,
        RIVER_SEA_TR,
        RIVER_SEA_DR,
        RIVER_SEA_TL,
        RIVER_SEA_DL,
        RIVER_SEA_NT,
        RIVER_SEA_NR,
        RIVER_SEA_ND,
        RIVER_SEA_NL

}
